# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1fdc3ddb63a1e6b79680df36aaa7ff05d9431a5acefe999f6974ff24024dd40fe838259cf0c13c28fce533427a9cd218301bf41950fdc3b39f115e8e369f8a

test:
  secret_key_base: 1ed3f4588d60bbd2200aff4ee79604e3a57fe4f65133630e149c2a13531c9b9e92d048363f215a0516afda3a2819e9842a226bcb60b0cdd511d3677821f780c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
